

page_title: My proffesional career
contact_email: marek.bernd@gmail.com
contact_lab: This is my contact mail
copyright: School work (©) 2017
site_author: Marek Bernád
author_birthday: 1994

collections:
 hobbies:
      output: true
 sports:
      output: false

gems:
  - jemoji

# Build settings
markdown: kramdown
