

page_title: My proffesional career
contact_email: marek.bernd@gmail.com
contact_lab: This is my contact mail
copyright: School work (©) 2017
site_author: Marek Bernád
author_birthday: 1994

collections:
 hobbies:
      output: true
 sports:
      output: false

youtube:
    api_key: ae72421fa851c4eb9652966ade38865f4c80ca6d
videoid: ntj1J5mSZxI

gems:
  - jemoji

# Build settings
markdown: kramdown
